parameters:
    kernel.secret: '%env(APP_SECRET)%'
    jwt_secret: '%env(JWT_SECRET)%'


framework:
    secret: '%kernel.secret%'
    router:
        resource: '%kernel.project_dir%/src/Infra/Http/Controller/'
        type: attribute
    test: true
services:
    Src\Infra\Http\Security\JWT:
        arguments:
            $secret: '%jwt_secret%'
    _defaults:
        autowire: true
        autoconfigure: true

    Src\:
        resource: '../../../*'
        exclude: '../../../{DependencyInjection,Entity,Tests,Http/Config}'
when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
        Src\Domain\Repository\UserRepository:
            class: Tests\fake\FakeUserRepository
        Src\Domain\Repository\AccountRepository:
            class: Tests\fake\FakeAccountRepository
        Src\Domain\Repository\CategoryRepository:
            class: Tests\fake\FakeCategoryRepository
        Src\Domain\Repository\TransactionRepository:
            class: Tests\fake\FakeTransactionRepository
        Src\App\Security\TokenService:
            class: Tests\fake\FakeTokenService
        Src\Domain\Repository\SessionRepository:
            class: Tests\fake\FakeSessionRepository
